export { default as HeroSection } from './HeroSection'
export { default as WhyItMattersSection } from './WhyItMattersSection'
export { default as FeaturesSection } from './FeaturesSection'
export { default as ProcessSection } from './ProcessSection'
export { default as FeaturesHighlightSection } from './FeaturesHighlightSection'
export { default as CTASection } from './CTASection'
